context:
  version: "2.3.5"

package:
  name: ls-hpack
  version: ${{ version }}

source:
  url: https://github.com/litespeedtech/ls-hpack/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 430a1a36029e0ae1c81eaa0b2356920f1e65fde1cdd722351c671ebe513b7a96

build:
  skip: win
  script:
    - cmake -B _build -G Ninja ${CMAKE_ARGS} -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DSHARED=1 -DLSHPACK_XXH=1 .
    - cmake --build _build
    - install -d ${PREFIX}/lib ${PREFIX}/include
    - install -m 644 _build/libls-hpack.dylib ${PREFIX}/lib/ || install -m 644 _build/libls-hpack.so ${PREFIX}/lib/
    - install -m 644 lshpack.h ${PREFIX}/include/
    - install -m 644 lsxpack_header.h ${PREFIX}/include/
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('ls-hpack', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - ls-hpack

about:
  homepage: https://github.com/litespeedtech/ls-hpack
  summary: LiteSpeed HPACK (RFC7541) Library
  description: |
    LS-HPACK provides functionality to encode and decode HTTP headers using HPACK compression mechanism specified in RFC 7541.
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/litespeedtech/ls-hpack
  repository: https://github.com/litespeedtech/ls-hpack

extra:
  recipe-maintainers:
    - pavelzw
